# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gradiochat',
                'doc_host': 'https://Hopsakee.github.io',
                'git_url': 'https://github.com/Hopsakee/gradiochat',
                'lib_path': 'gradiochat'},
  'syms': {'gradiochat.core': {'gradiochat.core.foo': ('core.html#foo', 'gradiochat/core.py')}}}
